"""empty message

Revision ID: 37c9165a239b
Revises: 5a3357b9c3aa
Create Date: 2024-12-12 10:58:23.020474

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c9165a239b'
down_revision: Union[str, None] = '5a3357b9c3aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'borrows',
        sa.Column('book_id', sa.Integer(), nullable=False),
        sa.Column('reader_name', sa.String(), nullable=False),
        sa.Column('date_of_borrow', sa.Date(), nullable=False),
        sa.Column('date_of_return', sa.Date(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ['book_id'],
            ['books.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )
    op.create_unique_constraint(None, 'books', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_table('borrows')
    # ### end Alembic commands ###
